import = [
    "~/.config/alacritty/themes/themes/rose-pine-moon.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "none"

# Add dynamic padding for better readability
padding = { x = 5, y = 5 }

# Optimize for tmux
[scrolling]
multiplier = 5
history = 1000

[font]
normal.family = "MesloLGLDZ Nerd Font"
size = 8

# Add bold and italic variants for better code readability
bold = { family = "MesloLGLDZ Nerd Font", style = "Bold" }
italic = { family = "MesloLGLDZ Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGLDZ Nerd Font", style = "Bold Italic" }

# Offset is helpful for better font rendering
offset = { x = 0, y = 1 }
glyph_offset = { x = 0, y = 0 }

# Better cursor customization for programming
[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 750
unfocused_hollow = true

# Mouse configuration for better selection
[mouse]
hide_when_typing = true

# # Performance tweaks
# [debug]
# render_timer = false
# persistent_logging = false

