import = [
    "~/.config/alacritty/themes/themes/night_owl.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "none"

# Add dynamic padding for better readability
padding = { x = 5, y = 5 }

# Optimize for tmux
[scrolling]
multiplier = 5
history = 1000

[font]
normal.family = "MesloLGLDZ Nerd Font"
size = 14

# Add bold and italic variants for better code readability
bold = { family = "MesloLGLDZ Nerd Font", style = "Bold" }
italic = { family = "MesloLGLDZ Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGLDZ Nerd Font", style = "Bold Italic" }

# Offset is helpful for better font rendering
offset = { x = 0, y = 1 }
glyph_offset = { x = 0, y = 0 }

# Better cursor customization for programming
[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 750
unfocused_hollow = true

# Key bindings for common operations
[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

# Mouse configuration for better selection
[mouse]
hide_when_typing = true

# Selection configuration
[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# Performance tweaks
[debug]
render_timer = false
persistent_logging = false

# Better bell configuration for notifications
[bell]
animation = "EaseOutExpo"
duration = 0
