import = [
    "~/.config/alacritty/themes/themes/dracula.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
# padding.x = 10
# padding.y = 10

decorations = "none"

# opacity = 0.5
# blur = true

[font]
normal.family = "MesloLGLDZ Nerd Font"

#regular
size = 14

#for video
# size = 35.0
