import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "none"

# opacity = 0.9
blur = true

[font]
normal.family = "Monaspace Radon light"

#regular
size = 12

#for video
# size = 35.0
